apiVersion: istioapigateway.knative.dev/v1alpha1
kind: Route
metadata: 
  name: geoip-api
  namespace: istio-api-gateway
  annotations:
    route.istioapigateway.knative.dev/default-strip: "true"
spec:
  hosts:
  - api.example.io
  gateways:
  - web-api-gateway
  http:
  - name: no-auth-path-legacy
    match:
    - uri:
        prefix: /api/awesome/v1/login
    rewrite: 
      uri: /awesome-api/v1
    route:
    - destination: 
        host: some-api.legacy.io #! knative service host
    bypass-auth: false #! default is true
  - name: auth-path-with-knative
    match:
    - uri:
        prefix: /api/awesome/v1/login-check
    rewrite: 
      uri: /awosome-api/v1
    knative-serving-route: 
      name: awesome-api
      namespace: default
